runtime: python38

entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT

# Basic instance settings
instance_class: F1

# Define a single instance without scaling
manual_scaling:
  instances: 1

handlers:
- url: /.*
  script: auto
