name: ml_model_fast_api
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - git
  - pip
  - scikit-learn
  - pytest
  - jupyter
  - jupyterlab
  - fastapi
  - uvicorn
  - ydata-profiling=4.0.0
  - dvc
  - httpx
  - pytest-asyncio